# Vagrantfile
Vagrant.configure("2") do |config|
  # Servidor principal con HAProxy y Consul Server
  config.vm.define "servidorUbuntu" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "servidorUbuntu"
    server.vm.network "private_network", ip: "192.168.100.3"
    server.vm.provision "shell", path: "server-setup.sh"
    server.vm.network "forwarded_port", guest: 8080, host: 8080 # GUI HAProxy
  end

  # Primer servidor web con Consul Agent y Node.js
  config.vm.define "web1Ubuntu" do |web1|
    web1.vm.box = "ubuntu/jammy64"
    web1.vm.hostname = "web1Ubuntu"
    web1.vm.network "private_network", ip: "192.168.100.10"
    web1.vm.provision "shell", path: "web-setup1.sh"
  end

  # Segundo servidor web con Consul Agent y Node.js
  config.vm.define "web2Ubuntu" do |web2|
    web2.vm.box = "ubuntu/jammy64"
    web2.vm.hostname = "web2Ubuntu"
    web2.vm.network "private_network", ip: "192.168.100.11"
    web2.vm.provision "shell", path: "web-setup2.sh"
  end
end